# Generated by Django 4.0.4 on 2022-05-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patente', models.CharField(max_length=7)),
                ('Marca', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('TipoCarga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.IntegerField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Contacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Contacto', models.EmailField(max_length=254)),
            ],
        ),
    ]
